# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/chat_service.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'proto/chat_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/chat_service.proto\x12\x0binkpulse.ai\"/\n\x0b\x43hatRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\",\n\x0c\x43hatResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06is_end\x18\x02 \x01(\x08\x32R\n\x0b\x43hatService\x12\x43\n\nChatStream\x12\x18.inkpulse.ai.ChatRequest\x1a\x19.inkpulse.ai.ChatResponse0\x01\x42\x18\n\x14\x63om.inkpulse.grpc.aiP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.chat_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.inkpulse.grpc.aiP\001'
  _globals['_CHATREQUEST']._serialized_start=41
  _globals['_CHATREQUEST']._serialized_end=88
  _globals['_CHATRESPONSE']._serialized_start=90
  _globals['_CHATRESPONSE']._serialized_end=134
  _globals['_CHATSERVICE']._serialized_start=136
  _globals['_CHATSERVICE']._serialized_end=218
# @@protoc_insertion_point(module_scope)
