# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/vision_service.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'proto/vision_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/vision_service.proto\x12\x0binkpulse.ai\"S\n\x14ImageAnalysisRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x03 \x01(\t\"~\n\x15ImageAnalysisResponse\x12\x0f\n\x07is_book\x18\x01 \x01(\x08\x12 \n\x18is_electronically_marked\x18\x02 \x01(\x08\x12\x12\n\nconfidence\x18\x03 \x01(\x01\x12\x0e\n\x06reason\x18\x04 \x01(\t\x12\x0e\n\x06\x63\x61\x63hed\x18\x05 \x01(\x08\x32\x66\n\rVisionService\x12U\n\x0c\x41nalyzeImage\x12!.inkpulse.ai.ImageAnalysisRequest\x1a\".inkpulse.ai.ImageAnalysisResponseB\x18\n\x14\x63om.inkpulse.grpc.aiP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.vision_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.inkpulse.grpc.aiP\001'
  _globals['_IMAGEANALYSISREQUEST']._serialized_start=43
  _globals['_IMAGEANALYSISREQUEST']._serialized_end=126
  _globals['_IMAGEANALYSISRESPONSE']._serialized_start=128
  _globals['_IMAGEANALYSISRESPONSE']._serialized_end=254
  _globals['_VISIONSERVICE']._serialized_start=256
  _globals['_VISIONSERVICE']._serialized_end=358
# @@protoc_insertion_point(module_scope)
